{% set name = "jupyterlab-vega3" %}
{% set version = "3.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0e940ea443ffab48ae9e8e240a856a7470713b5640c29e7ddde2ddaacb748d76

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab >=4,<5
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/@jupyterlab/vega3-extension/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlab\\vega3-extension\\package.json (exit 0) else (exit 1)         # [win]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyterlab/jupyter-renderers
  summary: JupyterLab - Vega 3 and Vega-Lite 2 Mime Renderer Extension
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab_vega3/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - fcollonval
    - jtpio
    - jasongrout
    - blink1073
