{% set name = "jupyterlab-vega3" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab-vega3-{{ version }}.tar.gz
  sha256: 2121ba30b950a41beadbe4433cd47c21cc66231d90a491783e16b0f2d4e614bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8.0
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/@jupyterlab/vega3-extension/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlab\\vega3-extension\\package.json (exit 0) else (exit 1)         # [win]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/jupyter-renderers
  summary: JupyterLab - Vega 3 and Vega-Lite 2 Mime Renderer Extension
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - jasongrout
    - blink1073
